// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Quest struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	Type        string             `json:"type"`
	Status      string             `json:"status"`
	ImageUrl    string             `json:"image_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type QuestEntry struct {
	ID        pgtype.UUID        `json:"id"`
	QuestID   pgtype.UUID        `json:"quest_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Type      string             `json:"type"`
	Content   []byte             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	Username    string             `json:"username"`
	DisplayName *string            `json:"display_name"`
	AvatarUrl   *string            `json:"avatar_url"`
	Bio         *string            `json:"bio"`
	IsVerified  bool               `json:"is_verified"`
	VerifiedAt  pgtype.Timestamptz `json:"verified_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type UserAccount struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Provider       string             `json:"provider"`
	ProviderUserID *string            `json:"provider_user_id"`
	Password       []byte             `json:"password"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
