// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Quest struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      string             `json:"user_id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	Type        string             `json:"type"`
	Status      string             `json:"status"`
	ImageUrl    string             `json:"image_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type QuestEntry struct {
	ID        pgtype.UUID        `json:"id"`
	QuestID   pgtype.UUID        `json:"quest_id"`
	UserID    string             `json:"user_id"`
	Type      string             `json:"type"`
	Content   []byte             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID          string             `json:"id"`
	Username    string             `json:"username"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   *string            `json:"avatar_url"`
	Bio         *string            `json:"bio"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
