// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateQuest(ctx context.Context, arg CreateQuestParams) (Quest, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetQuest(ctx context.Context, id pgtype.UUID) (Quest, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListQuests(ctx context.Context) ([]Quest, error)
	ListUsers(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
