// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateQuest(ctx context.Context, arg CreateQuestParams) (Quest, error)
	CreateQuestEntry(ctx context.Context, arg CreateQuestEntryParams) (QuestEntry, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetQuest(ctx context.Context, id pgtype.UUID) (Quest, error)
	GetQuestForShare(ctx context.Context, id pgtype.UUID) (Quest, error)
	GetUserById(ctx context.Context, id string) (User, error)
	GetUserByIdForShare(ctx context.Context, id string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListQuestEntries(ctx context.Context, questID pgtype.UUID) ([]QuestEntry, error)
	ListQuests(ctx context.Context) ([]Quest, error)
	ListUsers(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
