// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuest = `-- name: CreateQuest :one
INSERT INTO quests (name, description, reward)
VALUES ($1, $2, $3)
RETURNING id, name, description, reward, created_at, updated_at
`

type CreateQuestParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Reward      int32  `json:"reward"`
}

func (q *Queries) CreateQuest(ctx context.Context, arg CreateQuestParams) (Quest, error) {
	row := q.db.QueryRow(ctx, createQuest, arg.Name, arg.Description, arg.Reward)
	var i Quest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Reward,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuest = `-- name: GetQuest :one
SELECT id, name, description, reward, created_at, updated_at FROM quests
WHERE id = $1
`

func (q *Queries) GetQuest(ctx context.Context, id pgtype.UUID) (Quest, error) {
	row := q.db.QueryRow(ctx, getQuest, id)
	var i Quest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Reward,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQuests = `-- name: ListQuests :many
SELECT id, name, description, reward, created_at, updated_at FROM quests
`

func (q *Queries) ListQuests(ctx context.Context) ([]Quest, error) {
	rows, err := q.db.Query(ctx, listQuests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quest{}
	for rows.Next() {
		var i Quest
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Reward,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
