// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuest = `-- name: CreateQuest :one
INSERT INTO quests (user_id, title, description, type, status, image_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, title, description, type, status, image_url, created_at, updated_at
`

type CreateQuestParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Title       string      `json:"title"`
	Description *string     `json:"description"`
	Type        string      `json:"type"`
	Status      string      `json:"status"`
	ImageUrl    string      `json:"image_url"`
}

func (q *Queries) CreateQuest(ctx context.Context, arg CreateQuestParams) (Quest, error) {
	row := q.db.QueryRow(ctx, createQuest,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.Status,
		arg.ImageUrl,
	)
	var i Quest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuest = `-- name: GetQuest :one
SELECT id, user_id, title, description, type, status, image_url, created_at, updated_at
FROM quests
WHERE id = $1
`

func (q *Queries) GetQuest(ctx context.Context, id pgtype.UUID) (Quest, error) {
	row := q.db.QueryRow(ctx, getQuest, id)
	var i Quest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQuests = `-- name: ListQuests :many
SELECT id, user_id, title, description, type, status, image_url, created_at, updated_at
FROM quests
`

func (q *Queries) ListQuests(ctx context.Context) ([]Quest, error) {
	rows, err := q.db.Query(ctx, listQuests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quest{}
	for rows.Next() {
		var i Quest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.Status,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
